import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div style={{
          display: "flex",
          flexDirection: "column",
          justifyContent: "space-between",
          height: "100%"
        }}>
          <header>
            <p style={{
              backgroundColor: "purple",
              padding: "1rem",
              color: "whitesmoke"
            }}>AI Stack</p>
          </header>
          <div style={{}}>
          {children}
          </div>
          <footer style={{}}>
            <p style={{
              backgroundColor: "gray",
              padding: "1rem"
            }}>QTIMinds</p>
          </footer>
        </div>
      </body>
    </html>
  );
}
